require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
