env:
  RUBY_VERSION: 3.0.0
  RUBOCOP_VERSION: 1.10.0
  RUBOCOP_RSPEC_VERSION: 2.2.0
  REEK_VERSION: 6.0.3

name: Rspec tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.65.0
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: |
          gem install rubocop -v ${{ env.RUBOCOP_VERSION }}
          gem install rubocop-rspec -v ${{ env.RUBOCOP_RSPEC_VERSION }}
      - name: Check code
        run: rubocop -c .rubocop.yml
  reek-test:
    name: Reek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.65.0
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install reek
        run: |
          gem install reek -v ${{ env.REEK_VERSION }}
      - name: Check code
        run: reek -c .reek.yml
  rspec-test:
    name: RSpec
    needs: 
      - rubocop-test
      - reek-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.65.0
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
        env:
          PARSER_ENV: test
      - name: Run tests
        run: bundle exec rspec
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
